---
title: "Project"
output:
  pdf_document: default
  word_document: default
  html_document: default
date: "2022-11-17"
---

```{r}
#Data Science project by
#Jenil Sheth : 7754395981
#Shruti More : 528873433
#Vedant Patil : 235168671
#Collin Taylor : 563919675
```

```{r}
library(readr)
library(imputeTS)
library(ggplot2)
library(kernlab)
library(caret)
library(tidyverse)
library(dplyr)
library(rio)
library(rpart)
library(rpart.plot)
library(e1071)
library(arules)
library(arulesViz)
library(rsample)
library(ggmap)
library(mapproj)
# library(sf)
# library(units)
library(shiny)
library(shinyWidgets)
```



```{r}

data <- read_csv("https://intro-datascience.s3.us-east-2.amazonaws.com/HMO_data.csv")
proj_df <- data.frame(data)
str(proj_df)
summary(proj_df)
```



```{r}

any(is.na(proj_df$X))
any(is.na(proj_df$age))
any(is.na(proj_df$bmi))
proj_df$bmi <- na.interpolation(proj_df$bmi, option = "linear")
any(is.na(proj_df$bmi))
any(is.na(proj_df$children))
any(is.na(proj_df$smoker))
any(is.na(proj_df$location))
any(is.na(proj_df$location_type))
any(is.na(proj_df$hypertension))
proj_df$hypertension <- na.interpolation(proj_df$hypertension)
any(is.na(proj_df$hypertension))
any(is.na(proj_df$cost))

proj_df$state_name <- proj_df$location
quantile(proj_df$cost)
proj_df$expensive <- with(proj_df, ifelse(cost > 4775, "TRUE", "FALSE"))
proj_df$expensive <- proj_df$cost>4775
Expensive <- proj_df %>% group_by(expensive) %>% filter(expensive=="TRUE")
InExpensive <- proj_df %>% group_by(expensive) %>% filter(expensive=="FALSE")
head(proj_df)
str(proj_df)
```

```{r}
mean(Expensive$bmi)
mean(Expensive$age)
mean(Expensive$children)
```


```{r}
mean(InExpensive$bmi)
mean(InExpensive$age)
mean(InExpensive$children)
```

```{r}
ggplot(InExpensive, aes(x=age,y=cost))+geom_point() + ggtitle("Age Vs Cost of Inexpensive People")
ggplot(Expensive, aes(x=age,y=cost))+geom_point() + ggtitle("Age Vs Cost of Expensive People")
```

```{r}
ggplot(proj_df, aes(x=age,y=cost))+geom_point() + ggtitle("Age Vs Cost")
ggplot(proj_df, aes(x=smoker,y=cost))+geom_point() + ggtitle("Smoker Vs Cost")
ggplot(proj_df, aes(x=bmi,y=cost))+geom_point() + ggtitle("BMI Vs Cost")
ggplot(proj_df, aes(x=exercise,y=cost))+geom_point() + ggtitle("Exercise Vs Cost")
ggplot(proj_df, aes(x=hypertension,y=cost))+geom_point() + ggtitle("Hypertension Vs Cost")
ggplot(proj_df, aes(x=location_type,y=cost))+geom_point() + ggtitle("Location Type Vs Cost")
ggplot(proj_df, aes(x=location,y=cost))+geom_point() + ggtitle("Location Vs Cost")
ggplot(proj_df, aes(x=children,y=cost))+geom_point() + ggtitle("Number of Children Vs Cost")
```

```{r}
sctr_plot <- ggplot(proj_df)
sctr_plot <- sctr_plot + aes(x =yearly_physical, y=cost, color = smoker)
sctr_plot <- sctr_plot + geom_point()
sctr_plot
```

```{r}
sctr_plot <- ggplot(proj_df)
sctr_plot <- sctr_plot + aes(x=age, y=cost, color = smoker)
sctr_plot <- sctr_plot + geom_point()
sctr_plot
```

```{r}
sctr_plot <- ggplot(proj_df)
sctr_plot <- sctr_plot + aes(x=bmi, y=location, color = location_type)
sctr_plot <- sctr_plot + geom_point()
sctr_plot
```

```{r}
sctr_plot <- ggplot(proj_df)
sctr_plot <- sctr_plot + aes(x=bmi, y=cost, color = smoker)
sctr_plot <- sctr_plot + geom_point()
sctr_plot
```


```{r}
sctr_plot <- ggplot(proj_df)
sctr_plot <- sctr_plot + aes(x=bmi, y=cost, color = exercise)
sctr_plot <- sctr_plot + geom_point()
sctr_plot
```

```{r}
sctr_plot <- ggplot(proj_df)
sctr_plot <- sctr_plot + aes(x=bmi, y=cost, color = hypertension)
sctr_plot <- sctr_plot + geom_point()
sctr_plot
```

```{r}
ggplot(proj_df) + aes(x=exercise) + geom_bar()
ggplot(proj_df) + aes(x=location_type) + geom_bar()
ggplot(proj_df) + aes(x=location) + geom_bar()
ggplot(proj_df) + aes(x=children) + geom_bar()
ggplot(proj_df) + aes(x=expensive) + geom_bar()
```


```{r}
us <- map_data("state")
#View(us)
us$state_name <- tolower(us$region)
proj_df$state_name <- tolower(proj_df$state_name)
mapping <- merge(us,proj_df,by="state_name")
mapping <- mapping[order(mapping$order),]
#View(mapping)
```

```{r}

```

```{r}
map <- ggplot(us, aes(map_id="state"))
map <- map + aes(x=long, y=lat, group=group) + geom_polygon(fill = "white", color = "black")
map <- map + expand_limits(x=us$long, y=us$lat)
map <- map + coord_map("mercator") + ggtitle("Expensive data as per Location")
map <- map + geom_point(data=mapping,aes(x=long,y=lat,colour=expensive),inherit.aes =F)
map
```

```{r}
dfAgg1 <- proj_df %>% group_by(location) %>% summarise(total_cost = mean(cost))
dfAgg1$state <- tolower(dfAgg1$location)
#View(dfAgg1)
us <- map_data("state")
#View(us)
us$state_name <- tolower(us$region)
dfAgg1$state_name <- tolower(dfAgg1$state)
mapping <- merge(us,dfAgg1,by="state_name")
mapping <- mapping[order(mapping$order),]
#View(mapping)
```

```{r}
map <- ggplot(mapping)+ geom_polygon(aes(x=long, y=lat, group=group, fill = total_cost),color="black")+ ggtitle("Cost as per Location")
map <- map + scale_fill_continuous(low = "white", high = "blue", name = "total_cost", label = scales::comma) +coord_map()
map
```

```{r}
us <- map_data("state")
us$state_name = tolower(us$region)
proj_df$location <- tolower(proj_df$location)
dfMerged <- merge(proj_df, us, all.y = TRUE, by.x="location", by.y = "state_name")
dfMerged <- dfMerged %>% arrange(order)
map <- ggplot(dfMerged)
map <- map + aes(x=long, y=lat, group=group, fill=smoker) + geom_polygon(color = "black")
map <- map + expand_limits(x=dfMerged$long, y=dfMerged$lat)
map <- map + coord_map() + ggtitle("State-Wise Smoker Distribution")
map
```


```{r}
us <- map_data("state")
us$state_name = tolower(us$region)
proj_df$location <- tolower(proj_df$location)
dfMerged <- merge(proj_df, us, all.y = TRUE, by.x="location", by.y = "state_name")
dfMerged <- dfMerged %>% arrange(order)
map <- ggplot(dfMerged)
map <- map + aes(x=long, y=lat, group=group, fill=bmi) + geom_polygon(color = "black")
map <- map + expand_limits(x=dfMerged$long, y=dfMerged$lat)
map <- map + coord_map() + ggtitle("State-Wise BMI Distribution")
map
```

```{r}
hist(proj_df$age)
hist(proj_df$bmi)
hist(proj_df$children)
hist(proj_df$hypertension)
hist(proj_df$cost)
```

```{r}
ggplot(proj_df)+aes(x=age,y=cost,)+geom_boxplot()+ ggtitle("Box Plot of Age Vs Cost")
ggplot(proj_df)+aes(x=bmi,y=cost)+geom_boxplot()+ ggtitle("Box Plot of BMI Vs Cost")
ggplot(proj_df)+aes(x=smoker,y=cost)+geom_boxplot()+ ggtitle("Box Plot of Smoker Vs Cost")
ggplot(proj_df)+aes(x=yearly_physical,y=cost)+geom_boxplot()+ ggtitle("Box Plot of Yearly Physical Vs Cost")
ggplot(proj_df)+aes(x=exercise,y=cost)+geom_boxplot()+ ggtitle("Box Plot of Exercise Vs Cost")
ggplot(proj_df)+aes(x=hypertension,y=cost)+geom_boxplot()+ ggtitle("Box Plot of Hypertension Vs Cost")
```


1. Multiple regression model
```{r}
mrLmOut <- lm(expensive ~ age+bmi+hypertension+smoker+exercise,proj_df)
summary(mrLmOut)
```

Conversion to factors
```{r}
proj_fact <- data.frame(
  #X= as.factor(proj_df$X),
  age= (proj_df$age),
  bmi = (proj_df$bmi),
  #children = as.factor(proj_df$children),
  smoker = (proj_df$smoker),
  #location = as.factor(proj_df$location),
  #location_type = as.factor(proj_df$location_type),
  #education_level = as.factor(proj_df$education_level),
  yearly_physical = (proj_df$yearly_physical),
  exercise = (proj_df$exercise),
  #married = as.factor(proj_df$married),
  hypertension = (proj_df$hypertension),
  #gender = (proj_df$gender),
  #cost= (proj_df$cost),
  expensive = as.factor(proj_df$expensive)
)
```

SVM MODELS
```{r}
proj_df$expensive <- as.factor(proj_df$expensive)
TrnList <- createDataPartition(y=proj_df$expensive, p=.60,list=FALSE)
TrnSet <- proj_df[TrnList,]
TstSet <- proj_df[-TrnList,]
#proj_df$expensive <- as.factor(proj_df$expensive)
#View(TrnSet)
```

```{r}

SVMmod <- ksvm(data = TrnSet, expensive~ age+bmi+children+smoker+hypertension+exercise+yearly_physical, C=5, Cross=3, prob.model= TRUE)
summary(SVMmod)
svmPredict <- predict(SVMmod, newdata = TstSet, type = "response" )
confusionMatrix(svmPredict,as.factor(TstSet$expensive))
```

Apriori Algorithm 
```{r}
data_apr <- proj_fact
data_apr <- as(data_apr,'transactions')
```


```{r}
proj_rules <- apriori(data_apr,
 parameter=list(supp=0.030, conf=0.7),
 control=list(verbose=F),
 appearance=list(default="lhs",rhs=("expensive=TRUE")))

summary(proj_rules)
#inspect(proj_rules)
```

Tree Model
```{r}
proj_rpart <- rpart(expensive ~ age+bmi+children+smoker+hypertension+exercise+yearly_physical, data = TrnSet, method = "class")
rpart_Pred <- predict(proj_rpart, newdata= TstSet, type= "class")

confusionMatrix(rpart_Pred, TstSet$expensive)
rpart.plot(proj_rpart)
```

Association Rule
```{r}
#asso_Data <- proj_fact[,-7]
#asso_Data[,1:14] <- lapply(asso_Data[,1:7],factor)
#str(asso_Data)
```


```{r}
our_Model3 <- proj_rpart
saveRDS(our_Model3,file="/Users/vedantpatil/Documents/IDS Project/our_Model3.rds")
readRDS(file="/Users/vedantpatil/Documents/IDS Project/our_Model3.rds")
library(shiny)
library(shinydashboard)

```

```{r}
library(shiny)
library(caret)
library(kernlab)
library(e1071)
library(tidyverse)
ui <- fluidPage (
  setBackgroundColor(
  color = c("#F7FBFF", "#2171B5"),
  gradient = "linear",
  direction = "bottom"),
  h1("IDS Project Group 4"),
  hr(),
  br(),
  # div("div creates segments of text with a similar style. This division of text is all blue because I passed the argument 'style = color:blue' to div", style = "color:blue"),
  h4(p(em("This App gives predictions based on the Rpart model"))),
  hr(),
  #Read the data
  fileInput("upload", label="UPLOAD SAMPLE TEST FILE", accept = c(".csv")),
  #Read the actual (solution) data
  fileInput("upload_Solution", label="UPLOAD SOLUTION FILE", accept = c(".csv")),
  #get a number (how much of the dataframe to show)
  numericInput("n", "Number of Rows", value = 5, min = 1, step = 1),
  #a place to output a table (i.e., a dataframe)
  tableOutput("headForDF"),
  #output the results (for now, just simple text)
  verbatimTextOutput("txt_results", placeholder = TRUE)
)

server <- function(input, output, session) {
  #load a model, do prediction and compute the confusion matrix
  use_model_to_predict <- function(df, df_solution){
    #load the pre-built model, we named it ‘out_model.rda’)
    my_model <- readRDS("/Users/vedantpatil/Documents/IDS Project/our_Model3.rds")
    
    print('enter')
    prd <- predict(my_model, df, type = "class")
    #show how the model performed
    print(prd)
    #glimpse(df)
    #df_solution$isexpensive<- as.factor(df_solution$isexpensive)
    confusionMatrix(prd, as.factor(df_solution$expensive))
  }
  #require an input file, then read a CSV file
  getTestData <- reactive({ 
    req(input$upload)
    read_csv(input$upload$name)
  })
  #require an the actual values for the prediction (i.e. solution file)
  getSolutionData <- reactive({ 
    req(input$upload_Solution)
    read_csv(input$upload_Solution$name) 
  })
  output$txt_results <- renderPrint({
    #load the data
    dataset <- getTestData() 
    dataset_solution <- getSolutionData()
    #load and use the model on the new data
    use_model_to_predict(dataset, dataset_solution)
  })
  #show a few lines of the dataframe
  output$headForDF <- renderTable({
    df <- getTestData()
    head(df, input$n)
  })
}
shinyApp(ui, server)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
